version: "3"

networks:
  autocovid-v2:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services: 
  mongo:
    image: mongo:bionic
    networks: 
      autocovid-v2:
        ipv4_address: 172.20.0.10
    ports: 
      - 37017:27017
  
  sanicapp:
    build:
      context: .
      dockerfile: ./dockerfile
    environment: 
      DOCKER-MONGO-HOST: 172.20.0.10
      DOCKER-MONGO-PORT: 27017
      DOCKER-AUTHCODE: authcode
    networks: 
      autocovid-v2:
        ipv4_address: 172.20.0.20
    volumes:
      - ./logs:/logs
    ports: 
      - 32768:8080

