version: "3"

services:
  webapi:
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      DOCKER-MONGO-HOST: mongo
      DOCKER-MONGO-PORT: 27017
      DOCKER-AUTHCODE: authcode
    network_mode: bridge
    external_links:
      - mongo:mongo
    volumes:
      - ./logs:/logs
    ports:
      - 32768:8080
